### ISSUE TITLE
'export' missing from 'decare module'

### ISSUE THREAD

**Issue by entith** [originalmoose/Typescript.Definitions.Tools#2]
The main `index.d.ts` file generated doesn't seem to have any means of adding the `export` keyword to the `declare module` line. Unless I am missing something, wouldn't this make it impossible to consume the module from other files?

**Comment by originalmoose** [comment]
I don't seem to be having any issues using the definitions I've generated and they don't contain the `export` keyword. From the example's I have seen out there the `export` keyword doesn't seem to be necessary. A good example of a definition file without any top level exports is @types/node. 

You should be able to access the types generated without the need to import the module (as long as the definition is included in your ts project directory). The tricky part is when it comes to constants and enums. Constants and enums don't really work in d.ts files and so they generate as an actual ts file that must be compiled and included on the page. 

If like me you are using modules (`import X from "somewhere"`) then this setup is not ideal as you will need to most likely have the enums file in a separate typescript project and use the typings lib to pull it and the index.d.ts file into your main project. I am in the process of creating some overloads to create more module friendly enums and definitions.
